### ISSUE TITLE
vue dev tools not visible

### ISSUE THREAD

**Issue by Siddufed** [primefaces/sakai-vue-cli#15]
vue dev tools not visible

**Comment by JumperSash** [comment]
sigma-vue uses vue 3.x, so you need to use [vue js extension for vue 3.x](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg?hl=en )
And if you installed [vue js extension for vue 2.x](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en) then you need to disable it.
