### ISSUE TITLE
failed to npm install with node 16

### ISSUE THREAD

**Issue by laoshaw** [primefaces/sakai-vue-cli#18]
just upgraded to node 16 and realized sigma-vue failed to 'npm install' as it failed to build node-sass.

**Comment by laoshaw** [comment]
this is an upstream issue, until then node 14 has to be used for now.

**Comment by laoshaw** [comment]
in fact node-sass is deprecated and will never be updated, https://sass-lang.com/blog/libsass-is-deprecated an alternative must be used for the future otherwise you will never able to use node16+ for this project

**Comment by laoshaw** [comment]
"If you’re a user of Node Sass, migrating to Dart Sass is straightforward: just replace node-sass in your package.json file with sass. Both packages expose the same JavaScript API." here is my fix:

npm uninstall node-sass
npm i -D sass

after that node-16 works fine

**Comment by bk2222** [comment]
to migrate from node-sass to sass 
https://github.com/sass/migrator

npm install -g sass-migrator
sass-migrator module -d -v src/assets/layout/layout.scss

**Comment by tugcekucukoglu** [comment]
Please check with the latest version.
