### ISSUE TITLE
too many vulnerable packages

### ISSUE THREAD

**Issue by adarali** [primefaces/sakai-vue-cli#21]
![Screenshot from 2021-06-27 10-11-01](https://user-images.githubusercontent.com/71417893/123551673-0d82a580-d730-11eb-812d-50998ba4c886.png)
10 high vulnerabilities? why? Imagine someone who is new to front-end and installs those vulnerable packages.

**Comment by adarali** [comment]
using npm@7.19.0 got
28 vulnerabilities (3 low, 10 moderate, 15 high)

**Comment by tugcekucukoglu** [comment]
You can update the packages on your side. We would be grateful if you create a PR with the possible solution.
