### ISSUE TITLE
Help, Problem running

### ISSUE THREAD

**Issue by Rudison** [primefaces/sakai-vue-cli#23]
I downloaded the git version and installed the dependencies, but when running it requires the following error

![image](https://user-images.githubusercontent.com/6667805/129215003-8245bb2d-9e13-4fb1-a916-f75ffe825d6f.png)

 package.json
 
![image](https://user-images.githubusercontent.com/6667805/129215403-8aa0a737-806c-4eb7-9589-abc9876ace32.png)

**Comment by BetoProgram** [comment]
I downloaded the github version and I also got an error.

![error1](https://user-images.githubusercontent.com/33771382/129277745-a92ae47d-497b-4afa-8564-3240fc05d979.JPG)

![error2](https://user-images.githubusercontent.com/33771382/129277939-a30af80d-7ba5-437a-9751-077d6ac700e5.JPG)

**Comment by devtaha** [comment]
Same issue

**Comment by tugcekucukoglu** [comment]
Some packages updated. Please check package.json and then try to remove package-lock.json file and install it again. This file can be out of date.

**Comment by sysrun** [comment]
Same error on current master (17e0045c1298d7df8dd0e4a280d5d84e1da124e8) , fresh install - no package-lock - node 14.14.0

**Comment by sysrun** [comment]
Solution: update Vue to 3.2.2 in package.json - looks like there is a problem between versions 3.0.0 and 3.1.8
