### ISSUE TITLE
I've ported sakai-vue from vue-cli to Vite.

### ISSUE THREAD

**Issue by 3ig** [primefaces/sakai-vue-cli#29]
https://github.com/3ig/sakai-vue-vite

Switched Vue-cli to Vite and updated all the dependencies to their latest versions.
Build time on M1 MacBook Air is 3s. Hot reload is instant. 
Using Node v16 and up is recommended.
Enjoy :)

**Comment by sbscan** [comment]
Thanks for the great job! Vite is super, porting hard. Can you give some clues how to port. I couldn't find any documents.

**Comment by primadi** [comment]
thank you. it is a great job. How to change base_path ?

**Comment by tugcekucukoglu** [comment]
Great job.

Thank you!
