### ISSUE TITLE
FileUpload component issues - remove single file and "no files" template

### ISSUE THREAD

**Issue by papies** [primefaces/sakai-vue-cli#3]
In the demo (https://www.primefaces.org/sigma-vue/#/misc) and when integrating the component into an app, uploading a file and removing it via the X button triggers a javascript error (TypeError: Cannot read property 'files' of undefined).
Also, the component seems not to support the "<template #empty>" markup to specify the text to display when no file has been uploaded yet.

**Comment by ernestneomobile** [comment]
I have solved the 'removing issue' moving the module FileUpload code to my components folder and modifying the remove method for this one:

        remove(index) {
            this.clearInputElement();
            this.files.splice(index, 1);
        },

About the "<template #empty>" feature I suppose it was added in a newest primevue version. Anyway, if you need it, you can try to add the last FileUpload code to your components folder.

Hope it helps
Ernest

**Comment by papies** [comment]
Checked your suggestion on the removal, it works fine.
I'll try to update the whole component too. Thanks!
