### ISSUE TITLE
node 17 issue and fix

### ISSUE THREAD

**Issue by cilman** [primefaces/sakai-vue-cli#30]
replace those parts of your package.json

Fix for "npm run serve" 
"scripts": {
    "serve": "export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve",
    "build": "export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service build",
    "lint": "export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service lint"
  }
  
Fix for "npm install" (just replaced the node-sass with sass)
"devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-standard": "^5.1.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^7.0.0",
    "sass": "^1.43.4",
    "sass-loader": "^10.2.0"
  }
  
  You can search and find why those needed, this is a quick fix.

**Comment by tugcekucukoglu** [comment]
Thanks,
