### ISSUE TITLE
sample page for login and register

### ISSUE THREAD

**Issue by polinwei** [primefaces/sakai-vue-cli#4]
Could you provide two sample pages for  login and registration?

**Comment by cagataycivici** [comment]
If there is more demand, why not?

**Comment by laoshaw** [comment]
yes please, login and registration are essential for many use cases

**Comment by alijuniorbr** [comment]
please, login and registration are essential for admin pages

**Comment by bjorntj** [comment]
Yes, please add login and registration pages...

**Comment by zhangjiayu139** [comment]
please, login and registration are essential for admin pages

**Comment by taqawi** [comment]
Yes, please add these two pages.

**Comment by tugcekucukoglu** [comment]
Login, Error, NotFound and Access pages have added.

Thanks,
