### ISSUE TITLE
Project fails to run due to errors

### ISSUE THREAD

**Issue by BenHayat** [primefaces/sakai-vue-cli#5]
Hi;

Just downloaded the project. After install, I tried to run it but goy the following error:
---------------------
**error  in ./src/components/TableDemo.vue?vue&type=style&index=0&id=d349835e&scoped=true&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Cannot find module 'node-sass'
Require stack:
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\sass-loader\dist\index.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\sass-loader\dist\cjs.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\loader-runner\lib\loadLoader.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\loader-runner\lib\LoaderRunner.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\webpack\lib\NormalModule.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\webpack\lib\NormalModuleFactory.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\webpack\lib\Compiler.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\webpack\lib\webpack.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\@vue\cli-service\lib\commands\serve.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\@vue\cli-service\lib\Service.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at getDefaultSassImpl (C:\PrimeVue\Sigma\Sigma-Vue\node_modules\sass-loader\dist\index.js:198:10)
    at Object.loader (C:\PrimeVue\Sigma\Sigma-Vue\node_modules\sass-loader\dist\index.js:80:29)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/TableDemo.vue?vue&type=style&index=0&id=d349835e&scoped=true&lang=scss& 4:14-461 14:3-18:5 15:22-469   
 @ ./src/components/TableDemo.vue?vue&type=style&index=0&id=d349835e&scoped=true&lang=scss&
 @ ./src/components/TableDemo.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://172.20.1.165:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/components/Dashboard.vue?vue&type=style&index=0&id=aae30ed8&lang=scss&scoped=true&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Cannot find module 'node-sass'
Require stack:
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\sass-loader\dist\index.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\sass-loader\dist\cjs.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\loader-runner\lib\loadLoader.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\loader-runner\lib\LoaderRunner.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\webpack\lib\NormalModule.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\webpack\lib\NormalModuleFactory.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\webpack\lib\Compiler.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\webpack\lib\webpack.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\@vue\cli-service\lib\commands\serve.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\@vue\cli-service\lib\Service.js
- C:\PrimeVue\Sigma\Sigma-Vue\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at getDefaultSassImpl (C:\PrimeVue\Sigma\Sigma-Vue\node_modules\sass-loader\dist\index.js:198:10)
    at Object.loader (C:\PrimeVue\Sigma\Sigma-Vue\node_modules\sass-loader\dist\index.js:80:29)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Dashboard.vue?vue&type=style&index=0&id=aae30ed8&lang=scss&scoped=true& 4:14-461 14:3-18:5 15:22-469   
 @ ./src/components/Dashboard.vue?vue&type=style&index=0&id=aae30ed8&lang=scss&scoped=true&
 @ ./src/components/Dashboard.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://172.20.1.165:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js**

**Comment by tugcekucukoglu** [comment]
It looks like node-sass problem. `npm rebuild node-sass` could help.
