### ISSUE TITLE
Integrate with existing project

### ISSUE THREAD

**Issue by kushboojain** [primefaces/sakai-vue-cli#6]
There aren't any steps given on how do I integrate this with my existing Vue.js project

**Comment by tugcekucukoglu** [comment]
This added with the latest updates.

Thanks,

**Comment by DazDotOne** [comment]
@tugcekucukoglu where has this been added?

edit: Found it. For others looking to do this, it's in the Documentation menu item of sigma.
 
if you have it running locally:
http://localhost:8081/#/documentation

otherwise:
https://www.primefaces.org/sigma-vue/#/documentation
