### ISSUE TITLE
Will this be updated for PrimeVue-3 supporting Vue 3?

### ISSUE THREAD

**Issue by layanto** [primefaces/sakai-vue-cli#7]
Will this be updated for PrimeVue-3 supporting Vue 3?

**Comment by mertsincan** [comment]
Hi,

Yes, we're working on it now.

Best Regards,

**Comment by dhax** [comment]
Hi, nice to hear you are working on it right now. No pressure here, but can you maybe give a rough estimation on when you plan to release? Thank you.

**Comment by tugcekucukoglu** [comment]
Sigma-Vue supports PrimeVue3 and Vue3 now. Sorry for late answer.

Best regards,
